# Dev Dockerfile for O3DE Engine Development
# Minimal base setup for UID/GID bind mount compatibility

ARG BASE_IMAGE=ubuntu:22.04
FROM ${BASE_IMAGE}

# Avoid interactive tzdata prompt
ENV DEBIAN_FRONTEND=noninteractive

# Create non-root user placeholder
ARG USERNAME=devuser
ARG UID=1000
ARG GID=1000

# Add user and group
RUN groupadd -g $GID $USERNAME \
    && useradd -m -u $UID -g $GID -s /bin/zsh $USERNAME \
    && passwd -d $USERNAME \
    && apt-get update \
    && apt-get install -y \
        sudo \
        git \
        curl \
        ca-certificates \
        locales \
        tzdata \
        bash \
        zsh \
        nano \
        x11-apps \
        clang \
        lld \
        ninja-build \
        libunwind-dev \
        libzstd-dev \
        binutils \
        libglu1-mesa-dev \
        libfontconfig1-dev \
        libxcb-xinerama0 \
        libxcb-xinerama0-dev \
        libxcb-xkb-dev \
        libxcb-randr0 \
        libxcb-randr0-dev \
        libxkbcommon-x11-dev \
        libxkbcommon-dev \
        libxcb-xfixes0-dev \
        libxcb-xinput-dev \
        libxcb-xinput0 \
        libxcb-icccm4-dev \
        libxcb-image0-dev \
        libxcb-keysyms1-dev \
        libxcb-render-util0-dev \
        mesa-common-dev \
        libvulkan1 \
        libx11-dev \
        libpcre2-16-0 \
        libssl-dev \
        libcurl4-openssl-dev \
        pkg-config \
        libxcb-util0-dev \
        xcb-proto \
        libc6-dev \
        zlib1g-dev \
        libstdc++-12-dev \
        tix \
        software-properties-common \
        gnupg \
        xxd \
    && echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers \
    && locale-gen en_US.UTF-8 \
    # Manually install CMake 3.28.3 from official Kitware binaries
    && curl -LO https://github.com/Kitware/CMake/releases/download/v3.28.3/cmake-3.28.3-linux-x86_64.sh \
    && chmod +x cmake-3.28.3-linux-x86_64.sh \
    && ./cmake-3.28.3-linux-x86_64.sh --skip-license --prefix=/usr/local \
    && rm cmake-3.28.3-linux-x86_64.sh \
    # Add GCC 13 repo
    && add-apt-repository ppa:ubuntu-toolchain-r/test -y \
    && apt-get update \
    && apt-get install -y gcc-13 g++-13 \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 \
    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100

# Set environment and working dir
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
WORKDIR /home/$USERNAME

# Copy entrypoint
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
